common_args:
  training_type: "simulation"

data_args:
  dataset: "RSICB256"
  tr_percent: 0.8
  data_cache_dir: ~/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "resnet50"
  #model: "resnet56"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 30 #100
  client_num_per_round: 15
  comm_round: 40 #10
  epochs: 100
  batch_size: 32 #10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
  

validation_args:
  frequency_of_the_test: 1

device_args:
  worker_num: 4
  using_gpu: true
  gpu_mapping_file: yamls/gpu_mapping.yaml
  gpu_mapping_key: mapping_default

comm_args:
  backend: "MPI"
  is_mobile: 0


tracking_args:
  # the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: fedml
  wandb_name: fedml_torch_fedavg_mnist_lr
