common_args:
  training_type: "simulation"
  random_seed: 0
  config_version: "release"
  mlops_api_key: f5b88f5dca344e6faf17809139b89c48
  mlops_project_name: sp_fedavg_test
  mlops_run_name: fedml_torch_fedavg_mnist_lr_mlsys

data_args:
  dataset: "RSICB256"
  tr_percent: 0.8
  data_cache_dir: ~/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "resnet50"

train_args:
  federated_optimizer: "HierarchicalFL"
  client_id_list: "[]"
  client_num_in_total: 4
  client_num_per_round: 4
  comm_round: 200
  epochs: 1
  batch_size: 32
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
  group_method: "random"
  group_num: 8
  group_comm_round: 3
  lr: 0.001



validation_args:
  frequency_of_the_test: 1

device_args:
  using_gpu: true
  gpu_id: 0

comm_args:
  backend: "sp"

tracking_args:
  # the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_entity: fedml-ai
  wandb_project: simulation
  run_name: fedml_torch_hierachicalfl_mnist_lr
  using_mlops: false
