common_args:
  training_type: "simulation"

data_args:
  dataset: "RSICB256"
  tr_percent: 0.8
  data_cache_dir: ~/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "resnet50"
  #model: "resnet56"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 1000
  client_num_per_round: 4
  comm_round: 50
  epochs: 1
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
  momentum: 0.99

validation_args:
  frequency_of_the_test: 1

device_args:
  worker_num: 4
  using_gpu: true
  gpu_mapping_file: yamls/gpu_mapping.yaml
  gpu_mapping_key: mapping_default

comm_args:
  backend: "MPI"
  is_mobile: 0


tracking_args:
  log_file_dir: ./log
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: fedml
  wandb_name: fedml_torch_fedavg_mnist_lr
  using_mlops: false

attack_args:
  enable_attack: true #true
  attack_type: byzantine
  attack_mode: random # zero; random
  byzantine_client_num: 1

defense_args:
  enable_defense: false
  defense_type: robust_learning_rate
  beta: 0.25
  krum_param_m: 2
  byzantine_client_num: 1
  norm_bound: 5.0
  tau: 10
  bucket_size: 3
  trim_param_b: 1
  alpha: 0.95
  option_type: 2
  robust_threshold: 4
